--- 
abstract: ~
author: 
  - Akira Horimoto
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: App-CLI-Plugin-Config-YAML-Syck
no_index: 
  directory: 
    - inc
    - t
requires: 
  App::CLI::Extension: 0
  NEXT: 0
  Path::Class: 0
  YAML::Syck: 0
  perl: 5.8.0
version: 0.01
