---
abstract: 'for App::CLI::Extension config plugin module'
author:
  - 'Akira Horimoto'
build_requires:
  ExtUtils::MakeMaker: 6.30
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-CLI-Plugin-Config-YAML-Syck
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  App::CLI::Extension: 1
  Filter::Util::Call: 0
  YAML::Syck: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.0
